feat: Añadido Backend Edición Contraseña #240
ISPP-Grupo-10/cocemfe-sevilla pull request #241
Opened 2024-04-04 17:25 UTC by tcabgom

Para acceder a la pantalla hay que ir a professionals/change_password. Esto es debido a que esta pantalla está conectada a la de perfil de usuario, la cual no está creada todavía y es otra manera. De manera provisional lo he implementado así.

2024-04-05 08:55 UTC, JesusSolisOrtega commented
El código parece correcto, pero debería corregirse la pérdida de cobertura antes de mergear

2024-04-05 10:15 UTC, tcabgom commented
Estoy teniendo problemas con la cobertura. El commit donde se solucionan las pruebas se ha quedado atascado en el actions, y parece que hace que no detecte el coverage añadido. Voy a ver si puedo solucionarlo de alguna manera

2024-04-05 11:50 UTC, tcabgom commented
No logro hacer que el Codacy me valide la pull request.

He implementado un total de 18 pruebas de la funcionalidad y puedo confirmar que código que ha sido testeado aparece como no cubierto.

Lo mismo para el problema de la contraseña, que dice que no la valida antes de guardarla, y en el código se valida 3 veces

2024-04-05 12:05 UTC, tcabgom commented
Vale, acabo de descubrir que el fallo es que la integración continua no encuentra ninguna prueba

2024-04-05 12:05 UTC, Ignarrman requested changes
Lo he probado y no me funciona bien. Me he logeado como admin y he puesto las contraseñas bien y me dice que no estoy autenticado. 
![image](https://github.com/ISPP-Grupo-10/cocemfe-sevilla/assets/113461816/950e819f-6980-4d4a-ad50-1053cbe568c8)
Yo he puesto todo bien así que no se que puede ser.

2024-04-05 13:05 UTC, JesusSolisOrtega commented
ahora intenta comprobar que la contraseña antigua cumpla con el validador.

Esto no debe ser así ya que es posible crear un super usuario con una contraseña que no cumpla con esos estándares a través de comandos y le imposibilitas actualizarla debidamente.

2024-04-05 13:08 UTC, JesusSolisOrtega requested changes
No debe forzarse el validador custom en la contraseña antigua, ya que esta simplemente debe ser la correcta. Es solo la nueva la que debe comprobarse que cumple con los criterios de contraseña fuerte/aceptable.

2024-04-05 14:31 UTC, tcabgom commented
@JesusSolisOrtega Creo que estás confundiendo como funciona el código. Lo he mirado varias veces, se lo he pasado a una IA y no encuentro la parte en la que dices que le estoy aplicando el validador a la contraseña antigua. El método clean_old_password() simplemente comprueba que la contraseña del usuario es correcta (he descubierto que un if está duplicado en esa función, lo corregiré ahora) y en la función save() se está validando la contraseña nueva introducida, no la antigua.

De todas maneras si crees que me he equivocado en el análisis que he realizado dímelo.

Aun así cierto que la nueva contraseña se valida dos veces. El motivo es porque si no lo incluyo, Codacy me dice que estoy guardando una contraseña sin validarla porque no detecta que ha sido validada previamente.

Enlace a la conversación con el ChatGPT: https://chat.openai.com/share/d5a820c3-f969-4eb0-a0a5-35892f4e8fbb

2024-04-05 14:42 UTC, tcabgom commented
@Ignarrman Creo que simplemente no has puesto una contraseña lo suficientemente fuerte. En clean_old_password(), como le acabo de decir a Jesús, hay un if mal escrito que está haciendo que se manden mal los mensajes de error:
![imagen](https://github.com/ISPP-Grupo-10/cocemfe-sevilla/assets/113366030/782da483-5a41-48d1-bdbd-1523b74b2335)
Procedo a corregirlo poniendole un elif

2024-04-05 14:48 UTC, JesusSolisOrtega approved these changes
Acabo de comprobar la funcionalidad y ahora hace correctamente el cambio.

La diferencia de cobertura está mal. Al parecer alguien ha cambiado la configuración y no detecta correctamente los test. Se ha comunicado el problema. 

Los test ejecutan correctamente cuando seleccionas directamente la clase. De modo que se acepta la pull request teniendo en cuenta las circunstancias mencionadas.

2024-04-06 09:59 UTC, Ignarrman approved these changes
Tal y como dice @JesusSolisOrtega ya parece estar todo en orden y funciona correctamente. Apruebo el merge

2024-04-06 10:00 UTC, Ignarrman commented
Lo apruebo aunque no tenga lo del codacy, aún estamos estudiando la situación.

2024-04-06 10:00 UTC, merged