Feature/230 backend mi perfil Closes #230
ISPP-Grupo-10/cocemfe-sevilla pull request #243
Opened 2024-04-05 11:36 UTC by JesusSolisOrtega

Añadida la vista de usuarios

El frontend debe añadir dos botones, uno que lleve a la pantalla de edición de usuarios y otro para cambiar la contraseña.

Se accede introduciendo directamente la url: (host)/professionals/professional_data/2/

Se debe cambiar el acceso para que en vez de a la edición de usuario lleve a esta página. y desde esta página enlaza a dicha pantalla de edición.

2024-04-05 11:50 UTC, Ignarrman approved these changes
Vale ya entiendo la razón de tener la razón de tener las funciones de editar y visualizar separadas ya que al visualizar los usuarios no pueden ver todo.

Ya nos encargamos en el frontend que clickar en el nombre de usuario te lleve a visualizar y el botón del boli a editar. De momento ve arreglando los erroes que salgan del codacy y te mergeo cuando esten

2024-04-05 11:50 UTC, Ignarrman commented
Se me olvido añadir que todo funciona bien

2024-04-06 10:17 UTC, tcabgom requested changes
Parece que todo funciona correctamente.

Me parece raro que salga el campo de contraseña con un "no puede mostrarse" escrito, pero entiendo que eso es cosa del frontend.

El mergeo del cambio de contraseña con develop ha causado conflictos. Antes de mergear nada deben ser resueltos

2024-04-06 10:40 UTC, JesusSolisOrtega commented
Ya se han resuelto con conflictos.
Puedes volver a hacer la revisión oportuna.

2024-04-06 10:46 UTC, tcabgom commented
Te has equivocado de rama al solucionar los conflictos. Esta es una pull request para feature/230-backend-mi-perfil (f minúscula), pero estos han sido resuelto en Feature/230-backend-mi-perfil (F mayúscula).

No se cual es el motivo de eso pero a mí me ocurrió también hace dos sprints. Cambia la pull request o soluciona los conflictos en esta rama

2024-04-06 10:53 UTC, JesusSolisOrtega commented
Por algún motivo visual estudio está capitalizando la primera letra de las ramas y no me permite hacerlo en esta.
Lo solucionaré directamente desde github, ya que es una resolución sencilla.

2024-04-06 10:55 UTC, tcabgom commented
Perfecto. 

Muchas gracias por el descubrimiento, lo comunicaré al resto de miembros del grupo ya que esto puede afectar (y a afectado) a futuras pull request

2024-04-06 11:29 UTC, JesusSolisOrtega commented
Debido a problemas con el entorno sincronizándose con github se ha realizado la resolución del envio de contraseñas desde github. No obstante el problema se ha resuelto y comprobado en el entorno de trabajo, con sus debidas garantías y pruebas.

2024-04-06 11:32 UTC, tcabgom approved these changes
Perfecto, todo funciona correctamente. Buen trabajo

2024-04-06 11:33 UTC, merged